steps:
- uses: actions/checkout@v4
- uses: actions/setup-java@v4
  with:
    distribution: 'temurin' # See 'Supported distributions' for available options
    java-version: '21'
- run: java hgit3.java
